# Generated by Django 3.2.16 on 2022-12-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postAuthur', models.CharField(max_length=200)),
                ('postAuthurId', models.IntegerField()),
                ('postTitle', models.CharField(max_length=200)),
                ('postPrice', models.IntegerField()),
            ],
        ),
    ]
