# Generated by Django 3.2.16 on 2022-12-02 13:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='postImage',
            field=models.ImageField(default=datetime.datetime(2022, 12, 2, 13, 25, 0, 182225, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
