# Generated by Django 4.1.3 on 2022-12-04 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_posts_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='postCategory',
            field=models.CharField(default=datetime.datetime(2022, 12, 4, 16, 2, 44, 817818, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
    ]
