# Generated by Django 4.1.3 on 2022-12-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_posts_postcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postImage',
            field=models.ImageField(max_length=10000, upload_to=''),
        ),
    ]
