# Generated by Django 4.1.3 on 2022-12-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_posts_postauthur_remove_posts_postauthurid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='postCategory',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='posts',
            name='postImage',
            field=models.ImageField(default='null', max_length=10000, upload_to=''),
        ),
        migrations.AddField(
            model_name='posts',
            name='postTitle',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
