# Generated by Django 4.1.4 on 2022-12-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_posts_postcategory_posts_postimage_posts_posttitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='postImage',
        ),
    ]
