# Generated by Django 4.1.4 on 2022-12-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_posts_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='postImage',
            field=models.ImageField(default='null', max_length=10000, upload_to=''),
        ),
    ]
