# Generated by Django 4.1.4 on 2022-12-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_posts_postimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200, unique=True)),
                ('userContact', models.IntegerField()),
                ('userEmail', models.EmailField(default='null', max_length=254, unique=True)),
                ('userPassword', models.CharField(max_length=200)),
            ],
        ),
    ]
