# Generated by Django 4.1.4 on 2022-12-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='userPassword2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
