# Generated by Django 4.1.4 on 2023-01-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_users_alter_posts_postcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='postDescription',
            field=models.CharField(default='NO DESCRIPTION ADDED', max_length=1000000),
        ),
    ]
