# Generated by Django 4.1.6 on 2023-02-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_posts_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postImage',
            field=models.ImageField(default='noImg.png', max_length=10000, upload_to=''),
        ),
    ]
